In [56]:
import warnings
warnings.filterwarnings('ignore')

In [57]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules
import matplotlib.pyplot as plt

## Contoh 1

In [58]:
df=[['Pena', 'Roti', 'Mentega'],
    ['Roti', 'Mentega', 'Telur', 'Susu'],
    ['Buncis', 'Telur', 'Susu'],
    ['Roti', 'Mentega'],
    ['Roti', 'Mentega', 'Kecap', 'Telur', 'Susu']]

In [59]:
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(df).transform(df)

In [60]:
df_apriori = pd.DataFrame(te_ary, columns=te.columns_)
df_apriori

   Buncis  Kecap  Mentega   Pena   Roti   Susu  Telur
0   False  False     True   True   True  False  False
1   False  False     True  False   True   True   True
2    True  False    False  False  False   True   True
3   False  False     True  False   True  False  False
4   False   True     True  False   True   True   True

In [61]:
from mlxtend.frequent_patterns import apriori

frequent_itemsets=apriori(df_apriori, min_support=0.4, use_colnames=True)
frequent_itemsets

    support                      itemsets
0       0.8                     (Mentega)
1       0.8                        (Roti)
2       0.6                        (Susu)
3       0.6                       (Telur)
4       0.8               (Roti, Mentega)
5       0.4               (Mentega, Susu)
6       0.4              (Mentega, Telur)
7       0.4                  (Roti, Susu)
8       0.4                 (Roti, Telur)
9       0.6                 (Telur, Susu)
10      0.4         (Roti, Mentega, Susu)
11      0.4        (Roti, Mentega, Telur)
12      0.4        (Telur, Mentega, Susu)
13      0.4           (Roti, Telur, Susu)
14      0.4  (Roti, Mentega, Telur, Susu)

In [62]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]

,antecedents,consequents,support,confidence,lift
0,(Roti),(Mentega),0.8,1.000000,1.250000
1,(Mentega),(Roti),0.8,1.000000,1.250000
2,(Mentega),(Susu),0.4,0.500000,0.833333
3,(Susu),(Mentega),0.4,0.666667,0.833333
4,(Mentega),(Telur),0.4,0.500000,0.833333
5,(Telur),(Mentega),0.4,0.666667,0.833333
6,(Roti),(Susu),0.4,0.500000,0.833333
7,(Susu),(Roti),0.4,0.666667,0.833333
8,(Roti),(Telur),0.4,0.500000,0.833333
9,(Telur),(Roti),0.4,0.666667,0.833333
10,(Telur),(Susu),0.6,1.000000,1.666667
11,(Susu),(Telur),0.6,1.000000,1.666667
12,"(Roti, Mentega)",(Susu),0.4,0.500000,0.833333
13,"(Roti, Susu)",(Mentega),0.4,1.000000,1.250000
14,"(Mentega, Susu)",(Roti),0.4,1.000000,1.250000
15,(Roti),"(Mentega, Susu)",0.4,0.500000,1.250000
16,(Mentega),"(Roti, Susu)",0.4,0.500000,1.250000
17,(Susu),"(Roti, Mentega)",0.4,0.666667,0.833333
18,"(Roti, Mentega)",(Telur),0.4,0.500000,0.833333
19,"(Roti, Telur)",(Mentega),0.4,1.000000,1.250000
20,"(Mentega, Telur)",(Roti),0.4,1.000000,1.250000
21,(Roti),"(Mentega, Telur)",0.4,0.500000,1.250000
22,(Mentega),"(Roti, Telur)",0.4,0.500000,1.250000
23,(Telur),"(Roti, Mentega)",0.4,0.666667,0.833333
24,"(Mentega, Telur)",(Susu),0.4,1.000000,1.666667
25,"(Susu, Telur)",(Mentega),0.4,0.666667,0.833333
26,"(Mentega, Susu)",(Telur),0.4,1.000000,1.666667
27,(Telur),"(Mentega, Susu)",0.4,0.666667,1.666667
28,(Mentega),"(Susu, Telur)",0.4,0.500000,0.833333
29,(Susu),"(Mentega, Telur)",0.4,0.666667,1.666667
30,"(Roti, Telur)",(Susu),0.4,1.000000,1.666667
31,"(Roti, Susu)",(Telur),0.4,1.000000,1.666667
32,"(Susu, Telur)",(Roti),0.4,0.666667,0.833333
33,(Roti),"(Susu, Telur)",0.4,0.500000,0.833333
34,(Telur),"(Roti, Susu)",0.4,0.666667,1.666667
35,(Susu),"(Roti, Telur)",0.4,0.666667,1.666667
36,"(Roti, Mentega, Telur)",(Susu),0.4,1.000000,1.666667
37,"(Roti, Mentega, Susu)",(Telur),0.4,1.000000,1.666667
38,"(Susu, Roti, Telur)",(Mentega),0.4,1.000000,1.250000
39,"(Susu, Mentega, Telur)",(Roti),0.4,1.000000,1.250000
40,"(Roti, Mentega)","(Susu, Telur)",0.4,0.500000,0.833333
41,"(Roti, Telur)","(Mentega, Susu)",0.4,1.000000,2.500000
42,"(Roti, Susu)","(Mentega, Telur)",0.4,1.000000,2.500000
43,"(Mentega, Telur)","(Roti, Susu)",0.4,1.000000,2.500000
44,"(Mentega, Susu)","(Roti, Telur)",0.4,1.000000,2.500000
45,"(Susu, Telur)","(Roti, Mentega)",0.4,0.666667,0.833333
46,(Roti),"(Susu, Mentega, Telur)",0.4,0.500000,1.250000
47,(Mentega),"(Susu, Roti, Telur)",0.4,0.500000,1.250000
48,(Telur),"(Roti, Mentega, Susu)",0.4,0.666667,1.666667
49,(Susu),"(Roti, Mentega, Telur)",0.4,0.666667,1.666667

## Contoh 2

In [63]:
df=pd.read_excel('Data/apriori1.xlsx', header=None)
df.head()

      0     1     2
0  Susu   Teh  Gula
1   Teh  Gula  Roti
2   Teh  Gula   NaN
3  Susu  Roti   NaN
4  Susu  Gula  Roti

In [64]:
records = []  
for i in range(df.shape[0]):  
    records.append([str(df.values[i, j]) for j in range(df.shape[1]) if pd.notna(df.values[i, j])])
print(records)

[['Susu', 'Teh', 'Gula'], ['Teh', 'Gula', 'Roti'], ['Teh', 'Gula'], ['Susu', 'Roti'], ['Susu', 'Gula', 'Roti'], ['Teh', 'Gula'], ['Gula', 'Kopi', 'Susu'], ['Gula', 'Kopi', 'Susu'], ['Susu', 'Roti', 'Kopi'], ['Gula', 'Teh', 'Kopi']]

In [65]:
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(records).transform(records)

In [66]:
df_apriori = pd.DataFrame(te_ary, columns=te.columns_)
df_apriori

    Gula   Kopi   Roti   Susu    Teh
0   True  False  False   True   True
1   True  False   True  False   True
2   True  False  False  False   True
3  False  False   True   True  False
4   True  False   True   True  False
5   True  False  False  False   True
6   True   True  False   True  False
7   True   True  False   True  False
8  False   True   True   True  False
9   True   True  False  False   True

In [67]:
from mlxtend.frequent_patterns import apriori

apriori(df_apriori, min_support=0.5, use_colnames=True)

   support     itemsets
0      0.8       (Gula)
1      0.6       (Susu)
2      0.5        (Teh)
3      0.5  (Teh, Gula)

In [68]:
frequent_itemsets = apriori(df_apriori, min_support=0.5, use_colnames=True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

   support     itemsets  length
0      0.8       (Gula)       1
1      0.6       (Susu)       1
2      0.5        (Teh)       1
3      0.5  (Teh, Gula)       2

In [69]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]

  antecedents consequents  support  confidence  lift
0       (Teh)      (Gula)      0.5       1.000  1.25
1      (Gula)       (Teh)      0.5       0.625  1.25